# Generated by Django 4.1.7 on 2023-03-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lod',
            name='option',
            field=models.BooleanField(choices=[('Like', '👍'), ('Dislike', '👎')]),
        ),
    ]
