# Generated by Django 4.1.7 on 2023-03-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_device_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='binary',
            field=models.BinaryField(null=True),
        ),
    ]
