# Generated by Django 4.1.7 on 2023-03-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_device_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='binary',
            field=models.BinaryField(max_length=999999999, null=True),
        ),
    ]
