# Generated by Django 4.1.7 on 2023-03-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_device_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='binary',
            field=models.FloatField(null=True),
        ),
    ]
