# Generated by Django 4.1.7 on 2023-03-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_lod_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lod',
            name='option',
            field=models.BooleanField(choices=[(True, '👍'), (False, '👎')]),
        ),
    ]
