# Generated by Django 4.1.7 on 2023-03-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_lod_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='lod',
            name='option2',
            field=models.CharField(choices=[('👍', '👍'), ('👎', '👎')], max_length=30, null=True),
        ),
    ]
